---
title: "Exercise 1. Distributions - 1"
output: html_notebook
---

## Exercise 1. Distributions - 1
You may have noticed that numerical data is often summarized with the average value. For example, the quality of a high school is sometimes summarized with one number: the average score on a standardized test. Occasionally, a second number is reported: the standard deviation. So, for example, you might read a report stating that scores were 680 plus or minus 50 (the standard deviation). The report has summarized an entire vector of scores with with just two numbers. Is this appropriate? Is there any important piece of information that we are missing by only looking at this summary rather than the entire list? We are going to learn when these 2 numbers are enough and when we need more elaborate summaries and plots to describe the data.

Our first data visualization building block is learning to summarize lists of factors or numeric vectors. The most basic statistical summary of a list of objects or numbers is its distribution. Once a vector has been summarized as distribution, there are several data visualization techniques to effectively relay this information. In later assessments we will practice to write code for data visualization. Here we start with some multiple choice questions to test your understanding of distributions and related basic plots.

In the murders dataset, the region is a categorical variable and on the right you can see its distribution. To the closet 5%, what proportion of the states are in the North Central region?



## Exercise 2. Distributions - 2
In the murders dataset, the region is a categorical variable and to the right is its distribution.

Which of the following is true:

Instructions
50 XP
Possible Answers

The graph is a histogram.

The graph shows only four numbers with a bar plot.

Categories are not numbers so it does not make sense to graph the distribution.

The colors, not the height of the bars, describe the distribution.


## Exercise 3. Empirical Cumulative Distribution Function (eCDF)
The plot shows the eCDF for male heights:

Based on the plot, what percentage of males are shorter than 75 inches?



## Exercise 4. eCDF Male Heights
The plot shows the eCDF for male heights:

To the closest inch, what height m has the property that 1/2 of the male students are taller than m and 1/2 are shorter?

Instructions
50 XP
Possible Answers

61 inches

64 inches

69 inches

74 inches



## Exercise 5. eCDF of Murder Rates
Here is an eCDF of the murder rates across states.

Knowing that there are 51 states (counting DC) and based on this plot, how many states have murder rates larger than 10 per 100,000 people?

Instructions
50 XP
Possible Answers

1

5

10

50

Submit Answer


## Exercise 6. eCDF of Murder Rates - 2
Here is an eCDF of the murder rates across states:

Based on the eCDF above, which of the following statements are true:

Instructions
50 XP
Possible Answers

About half the states have murder rates above 7 per 100,000 and the other half below.

Most states have murder rates below 2 per 100,000.

All the states have murder rates above 2 per 100,000.

With the exception of 4 states, the murder rates are below 5 per 100,000.


## Exercise 7. Histograms
Here is a histogram of male heights in our heights dataset:

Based on this plot, how many males are between 62.5 and 65.5?

Instructions
50 XP
Possible Answers

11

29

58

99

Submit Answer



## Exercise 8. Histograms - 2
Here is a histogram of male heights in our heights dataset:

About what percentage are shorter than 60 inches?

Instructions
50 XP
Possible Answers

1%

10%

25%

50%

Submit Answer



## Exercise 9. Density plots
Based on this density plot, about what proportion of US states have populations larger than 10 million?

Instructions
50 XP
Possible Answers

0.02

0.15

0.50

0.55


## Exercise 10. Density plots - 2
Here are three density plots. Is it possible that they are from the same dataset? Which of the following statements is true:

Instructions
50 XP
Possible Answers

It is impossible that they are from the same dataset.

They are from the same dataset, but different due to code errors.

They are the same dataset, but the first and second undersmooth and the third oversmooths.

They are the same dataset, but the first does not have the x-axis in the log scale, the second undersmooths and the third oversmooths.
```{r}
plot(cars)
```













